name: DEV
on:
  repository_dispatch:
    types: [backend-master]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Echo
        run: echo "ref = ${{ github.event.client_payload.ref }}"