name: DEV
on:
  repository_dispatch:
    types: [backend-main, frontend-main]

concurrency:
  group: frontend-backend-integration
  cancel-in-progress: true

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:

      - name: Install tree
        run: sudo apt install tree -y

      - name: Echo directory
        run: tree -L 2

      - name: Echo status
        run: git status

      - name: Echo submodule status
        run: git submodule status