name: DEV
on:
  workflow_dispatch:
  repository_dispatch:
    types: [backend-main, frontend-main]

concurrency:
  group: frontend-backend-integration
  cancel-in-progress: true

jobs:

  test-frontend-backend:
    name: Test Frontend + Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'dev'
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Build Backend
        working-directory: ./backend
        run: mvn clean install -DskipTests

      - name: Setup Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: frontend/yarn.lock

      - name: Install Yarn
        run: npm install -g yarn

      - name: Compile Frontend
        working-directory: ./frontend
        run: yarn install && yarn build

      - name: Run End-to-End Tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          working-directory: ./frontend
          wait-on: "http://localhost:5000"
          wait-on-timeout: 30
          browser: chrome
          headless: true

  
  merge-to-main:
    name: Merge dev branch to staging
    runs-on: ubuntu-latest
    needs: [test-frontend-backend]
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: fregante/setup-git-user@v1
      - name: Merge
        run: |
          git checkout staging
          git merge dev --commit -m 'merge dev -> staging' 
          git push origin staging